# Generated by Django 2.1.7 on 2019-03-24 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_cartitem_line_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variations',
        ),
    ]
