# Generated by Django 2.1.7 on 2019-03-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_sub_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tax_total',
            new_name='tax',
        ),
    ]
