# Generated by Django 2.1.7 on 2019-03-06 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_total',
        ),
    ]
