# Generated by Django 2.1.7 on 2019-03-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20190319_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.13, max_digits=1000),
        ),
    ]
