# Generated by Django 2.1.5 on 2019-02-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190211_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='shade',
            field=models.ImageField(default=1, upload_to='products/images/'),
            preserve_default=False,
        ),
    ]
