# Generated by Django 2.1.7 on 2019-02-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190214_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('shade', 'shade'), ('package', 'package')], default='shade', max_length=120),
        ),
    ]
