# Generated by Django 2.1.7 on 2019-03-18 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
