# Generated by Django 2.1.7 on 2019-03-18 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_name'),
        ('products', '0015_remove_comment_author'),
    ]

    operations = [
    ]
