# Generated by Django 2.1.7 on 2019-03-19 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_comment_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'catogories',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='ratings',
            field=models.CharField(choices=[('⭐⭐⭐⭐⭐', '5'), ('⭐⭐⭐⭐', '4'), ('⭐⭐⭐', '3'), ('⭐⭐', '2'), ('⭐', '1')], default='★★★★★', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
            preserve_default=False,
        ),
    ]
